### ISSUE TITLE
Rebus eagerly commiting and disposing connections when I don't want it to

### ISSUE THREAD

**Issue by kasparkallas** [rebus-org/Rebus.PostgreSql#10]
Hello!

In my application, I want to put all database operations happening during a single HTTP request inside a corresponding transaction, so that everything fails or everything succeeds. Publishing through Rebus is a part of it. My application would have full control of the transactions.

A slight problem with Rebus arouse that Rebus would be eagerly commiting and disposing Npgsql transactions (reference: `PostgresqlTransport.cs`).

I solved it by configuring Rebus with a custom `IPostgresConnectionProvider` that provides a "connection" which can not be completed/finished:
```
public class NotFinishingPostgresConnection : PostgresConnection, IDisposable
{
    private readonly NpgsqlConnection _currentConnection;
    private readonly NpgsqlTransaction _currentTransaction;

    public NotFinishingPostgresConnection(NpgsqlConnection currentConnection, NpgsqlTransaction currentTransaction) : base(currentConnection, currentTransaction)
    {
        _currentConnection = currentConnection;
        _currentTransaction = currentTransaction;
    }

    public new Task Complete()
    {
        return Task.CompletedTask;
    }

    public new void Dispose()
    {
    }
}
```
The problem with this is that it uses quite ugly `new` keywords to achieve the functionality...

And even with this "not finishing connection", Rebus still somehow completed the transactions when there were multiple sendings/publishings through rebus during a request. I solved that by wrapping the HTTP request (using a ASP.NET MVC Middleware) in `RebusTransactionScope` that does nothing other than group the Rebus operations so that I could commit them later myself.

So I have the solutions and it's working correctly now. But I just wanted to do a little write-up if someone else has the same problem or something could be changed in the Rebus.PostgreSql code-base (e.g. make PostgresConnection's Complete() & Dispose() `virtual`).

**Comment by mookid8000** [comment]
Thanks for describing this issue 🙂 have you tried using the default Postgres provider together with `RebusTransactionScope`?

I would expect a single database transaction then, which would then be committed when the scope is completed.

**Comment by kasparkallas** [comment]
Thanks for answering

When I make my custom PostgresConnection return `return new PostgresConnection(npsqlTransactionAccessor.CurrentConnection, npsqlTransactionAccessor.CurrentTransaction);` then I get an ObjectDisposedException when I try to commit it later.

The default provider creates a new connection & transaction which is not what I want.

**Comment by mookid8000** [comment]
Hi @kasparkallas , I just made [this test](https://github.com/rebus-org/Rebus.PostgreSql/blob/master/Rebus.PostgreSql.Tests/Bugs/VerifyRebusTransactionScope.cs#L39), and as far as I can tell, only one single connection is created, even though 5 messages are sent.

Could you maybe try and disable your custom connection provider, and then just use `RebusTransactionScope` to bundle your outgoing messages?

Please let me know if it doesn't work out as expected. I'm closing this one for now 🙂
