### ISSUE TITLE
PerformExpiredMessagesCleanupCycle bugs and suggestion

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus.PostgreSql#16]
I'd like to point to several issues I've found in PerformExpiredMessagesCleanupCycle method.
1. In ctor of PostgresqlTransport there is no possibility to specify ExpiredMessagesCleanupInterval except default value.
2. Furthemore ExpiredMessagesCleanupInterval is never used, instead default interval 60 seconds is specified in asyncTaskFactory.Create method call.
3. And suggestion: why PerformExpiredMessagesCleanupCycle cleans up only messages of current recipient? 
In our case we use messages as short-live events, we don't care for event, after couple of minutes of event occurrence. And, for example one of our node has subscribed to events, and has died n the middle of process, without graceful un-subscription. It still will persist in subscription table, therefore causing to create events for it in messagequeue table. And moreover, no one will clean up it's messages, as each node cleans only respective queue events.
I suggest allow any database transport to cleanup any expired messages irrespectively from recipient.

**Comment by mookid8000** [comment]
Thanks for you bug report and suggestions.

Is it something you would like to help fixing?

**Comment by zabulus** [comment]
Currently 1 & 2 points don't block us.
Only 3 considers me a lot. If you OK with my suggestion, I could prepare PR, i think it's quite straightforward.
And another issue considers me - we have plans for using Rebus.SqlServer/4.0.0 and Rebus.PostgreSql/5.0.0 packages which are quite old. Our project still targets .NET 4.5.2, and mentioned packages are latest that support 4.5. Will you accept backport for these versions?

**Comment by mookid8000** [comment]
> Currently 1 & 2 points don't block us.

Ok, good. I'll see if I can get the time to fix it some time during the next couple of weeks.

> Only 3 considers me a lot. If you OK with my suggestion, I could prepare PR, i think it's quite straightforward.

Yes, definitely! 

> And another issue considers me - we have plans for using Rebus.SqlServer/4.0.0 and Rebus.PostgreSql/5.0.0 packages which are quite old. Our project still targets .NET 4.5.2, and mentioned packages are latest that support 4.5. Will you accept backport for these versions?

If you make the PR against the `release/5` branch, I will port the commit(s) forward to `master` as well.

**Comment by mookid8000** [comment]
Fixed by #17 – out in Rebus.PostgreSql 6.1.0 and 7.1.0, targeting Rebus 5 and 6 respectively.

**Comment by zabulus** [comment]
https://www.nuget.org/packages/Rebus.PostgreSql/5.0.0 targets rebus 4.0. 
Rebus 4.3.0 is the latest package that support .net 4.5.2. I know, it's quite old, but would you mind to backport also there?

**Comment by mookid8000** [comment]
sure – it's out in Rebus.PostgreSql 5.2.0
