### ISSUE TITLE
nuget pulls in npgsql 3.1.7

### ISSUE THREAD

**Issue by jmkelly** [rebus-org/Rebus.PostgreSql#2]
I'm in the process of updating the shootout project over on samples, and created a new one for the postgresql transport.  Unfortunately when I used nuget to load it, npgsql 3.1.7 was pulled in rather than 3.1.8.  I looked around and couldn't find anywhere to fix this in the repo, so I'll just leave this here.

**Comment by mookid8000** [comment]
argh bummer – it's Rebus.PostgreSql.nuspec that needs to be edited to match the version from package.config

**Comment by mookid8000** [comment]
it's fixed in 2.2.0 😄
