### ISSUE TITLE
Rebus.PostgreSql does not support schema config

### ISSUE THREAD

**Issue by evgenyshugaev** [rebus-org/Rebus.PostgreSql#29]
I got another problem: Rebus.PostgreSql does not support schema config like for ms sql server:

Configure.With(...)
.Transport(t => t.UseSqlServer(connectionString, "my-queue")
.WithSchema("rebus"))
.Start();

and for this reason table custom.bus_queue not created.
Can you add WithSchema("schrmaname") method to Configuration?

**Comment by patrick11994** [comment]
This issue is resolved by PR #33

**Comment by mookid8000** [comment]
And it's available on NuGet.org as Rebus.PostgreSql 8.2.0-b2 🙂
