### ISSUE TITLE
Make saga serializer configurable

### ISSUE THREAD

**Issue by mmdevterm** [rebus-org/Rebus.PostgreSql#30]
Hello!
While there is an option to pass JSON serializer settings when configuring Bus, these settings are only applied for transport, not for Saga.

`var jsonSerializerSettings = new JsonSerializerSettings();
...
 containerBuilder.RegisterRebus((configurer, context) => configurer
            .Serialization(s => s.UseNewtonsoftJson(jsonSerializerSettings))`.

It would be great to be able to configure Saga serializer for postgres, similarly to Rebus.SqlServer: https://github.com/rebus-org/Rebus.SqlServer/issues/59.

Would it be something you could achieve with a simple copy&paste? Maybe I could support you with this somehow?

Thanks in advance!

**Comment by mookid8000** [comment]
Yes definitely, as you've already discovered, Rebus' SQL Server saga persister allows for configuring the saga serializer, and I'm pretty sure a similar approach would work just fine with the Postgres persister.

If you're willing to make this change yourself, I'd be happy to assist you with submitting a PR.

You could start by forking the Rebus.PostgreSql repository and see if you can make the tests run. 🙂 Then it should be possible to use the same approach as with Rebus' SQL Server saga persister.

**Comment by mmdevterm** [comment]
Closing in favour of a created PR https://github.com/rebus-org/Rebus.PostgreSql/pull/31.
