### ISSUE TITLE
Add support for client certificate authentication

### ISSUE THREAD

**Issue by enriquein** [rebus-org/Rebus.PostgreSql#4]
We currently need to support using client certificates to authenticate against Postgres. Although the change is simple, I'm struggling to come up with a way to surface the functionality through the configuration extension methods.

The issue is that in order to configure Npgsql to use a client certificate, you need to add the certificate to the NpgsqlConnection object using the ProvideClientCertificatesCallback event. Seeing as Rebus wraps and hides the connection from the consumer, there is currently no way of providing the certificate.

I'd love submit a pull request implementing this functionality, but like I said, I have no idea how it would be best to provide this functionality. The way I currently had to work around this issue was that on our project I created a configuration function that uses my own ITimeoutManager implementation that in turn calls our own PostgresConnectionHelper. Of course, this is far from ideal.

Any guidance or ideas would be great.

**Comment by mookid8000** [comment]
Added by @enriquein  in 4.0.0-b05

**Comment by enriquein** [comment]
Any chance you could also release a v3 nuget with the change? We're currently using Rebus 3. I could pull request the v3 branch I'm currently pointing at to make it easier for you.

**Comment by mookid8000** [comment]
oh, sure! I'll just go create a `release/3` branch for you to PR against... just a moment

**Comment by mookid8000** [comment]
sorry for the long delay – I created the [`release/3`](https://github.com/rebus-org/Rebus.PostgreSql/tree/release/3) branch now

**Comment by enriquein** [comment]
Thanks! Pull request sent.
