### ISSUE TITLE
Not specifying "schemaName" throws exception.

### ISSUE THREAD

**Issue by robert-misura-tfs** [rebus-org/Rebus.PostgreSql#44]
Hi, I am currently trying to update to .NET 8. My service keep crashing on ArgumentNull exception. I debuged the code and it turned out that in [PostgreSqlSagaStorage](https://github.com/rebus-org/Rebus.PostgreSql/blob/master/Rebus.PostgreSql/PostgreSql/Sagas/PostgreSqlSagaStorage.cs) in the constructor 

```
public PostgreSqlSagaStorage(IPostgresConnectionProvider connectionHelper, string dataTableName, string indexTableName, IRebusLoggerFactory rebusLoggerFactory, ISagaSerializer sagaSerializer, string schemaName = null)
    {
        if (rebusLoggerFactory == null) throw new ArgumentNullException(nameof(rebusLoggerFactory));
        _connectionHelper = connectionHelper ?? throw new ArgumentNullException(nameof(connectionHelper));
        _dataTableName = new TableName(schemaName ?? TableName.DefaultSchemaName, dataTableName ?? throw new ArgumentNullException(nameof(dataTableName)));
        _indexTableName = new TableName(schemaName, indexTableName ?? throw new ArgumentNullException(nameof(indexTableName)));
        _sagaSerializer = sagaSerializer;
        _log = rebusLoggerFactory.GetLogger<PostgreSqlSagaStorage>();
    }
```

The '_indexTableName', since schemaName is null, new TableName falls into the argument exception. I am aware of the default schema name in [TableName](https://github.com/rebus-org/Rebus.PostgreSql/blob/master/Rebus.PostgreSql/PostgreSql/TableName.cs) but it keep falling into the argument exception.

```
   public TableName(string schema, string tableName)
    {
        if (schema == null) throw new ArgumentNullException(nameof(schema));
        if (tableName == null) throw new ArgumentNullException(nameof(tableName));

        Schema = StripQuotes(schema);
        Name = StripQuotes(tableName);
    }
```

I used to use it without schema name. It works when I add ... , schemaName: "public") at the end.  Configuration of the saga:

```
  public static void ConfigureSagas(this StandardConfigurer<ISagaStorage> s, string postgresConnectionString)
  {
      s.StoreInPostgres(postgresConnectionString, "sagas", "sagas-index", true);
  }
```

Is it problem on my site ? Or did anything change and schema is required now  ?

If schemaName is null, should it fall into the TableName controctor with default schemaName ? Also, I wonder, why it started to happen now ? Looks like that code was already there before, so I wonder what changed (except .NET 8)

PS: If owner still live in the Horsens, shoutout, I finished VIA UC in there 2 years ago.

**Comment by mookid8000** [comment]
It's a bug 😅 just a second

**Comment by mookid8000** [comment]
Could you try Rebus.PostgreSql 9.0.1 which is on NuGet.org now?
