### ISSUE TITLE
Outbox Table Schema Name

### ISSUE THREAD

**Issue by robert-misura-tfs** [rebus-org/Rebus.PostgreSql#45]
Hello, just to be sure, as there is a way to put schema name for the saga tables, outbox does not support this yet, am I right ? If no, is there a chance to add it ?

**Comment by robert-misura-tfs** [comment]
I think I found the solution. Just didn't notice the overload with TableName object.

` .Outbox(o => o.StoreInPostgreSql(postgresOptions.BuildConnectionString(),new TableName("schema-name", "outbox-table")))`

**Comment by mookid8000** [comment]
You found it! Great 🙂
